name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ENTRYPOINT: https://localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: 9KhpzKDOtxiC99mau2nW5Zwl # Required
          github-token: ${{ secrets.ACCESS_TOKEN }} #Optional 
          vercel-org-id: NL9xTmf3lB6rGO4iKRevnxg8  #Required
          vercel-project-id: prj_JtfKUFmunwEIalUny3MZIvVnpwBJ #Required 
          working-directory: ./pwa